### ISSUE TITLE
how can i get the database"itemVec_1M.o"

### ISSUE THREAD

**Issue by jiejie1993** [UlfbertHuynh/Scalable_hnsw#7]

**Comment by UlfbertHuynh** [comment]
The idea is that you have a set of vectors you want to index. The file "itemVec_1M.o" is just a file containing my specific set of vectors. You can randomize your own set of vectors and save it to the file "itemVec_1M.o" if you want.

Pseudo code is something like this: 
float[][] vecs = ...;//load(randomize) your set of vectors here
FloatCosineHandler handler = new FloatCosineHandler(); // VecHandler by default have the save vectors to file function, you don't necessarily need FloatCosineHandler
handler.save("itemVec_1M.o", vecs) ;

**Comment by jiejie1993** [comment]
I got it! thanks for your response,it's very helpful&nbsp;


郭玉杰
seu_gyj@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UlfbertHuynh"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 下午3:59
收件人: "UlfbertHuynh/scalable-hnsw"<scalable-hnsw@noreply.github.com&gt;; 
抄送: "东南大学郭玉杰"<384300189@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [UlfbertHuynh/scalable-hnsw] how can i get the database&quot;itemVec_1M.o&quot; (#7)





 
The idea is that you have a set of vectors you want to index. The file "itemVec_1M.o" is just a file containing my specific set of vectors. You can randomize your own set of vectors and save it to the file "itemVec_1M.o" if you want.
 
Pseudo code is something like this:
 float[][] vecs = ...;//load(randomize) your set of vectors here
 FloatCosineHandler handler = new FloatCosineHandler(); // VecHandler by default have the save vectors to file function, you don't necessarily need FloatCosineHandler
 handler.save("itemVec_1M.o", vecs) ;
